### ISSUE TITLE
engine null object bug

### ISSUE THREAD

**Issue by appleburger4** [Yoshubs/Forever-Engine#7]
got this one playing hypnos lullaby or something
----------
flixel/FlxState.hx (line 203)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 551)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/Yoshubs/Forever-Engine
----------
im no developer, but i was just instructed to put this mess here

**Comment by appleburger4** [comment]
https://user-images.githubusercontent.com/121481783/209631756-4342caef-e7b0-4613-a380-5d58f1c38593.mp4

**Comment by lemz1** [comment]
hypnos lullaby problems shouldnt be stated here, since this is the repository for the regular engine and not hypnos lullaby

**Comment by imdumlol** [comment]
here https://github.com/PopcornColonell/hypnosource

**Comment by BeastlyGhost** [comment]
mod errors shouldn't be put here, this is for ENGINE SPECIFIC errors unrelated to ANY mod
